### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by thardy** [getgauge/gauge-example-csharp#5]
When I follow these instructions on Windows, I receive the following error when navigating to localhost:8080...

load error: C:/Users/DevAdmin/AppData/Local/Temp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-1682902661320758583.dir/webapp/WEB-INF/config/environment -- java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean from org/jruby/RubyKernel.java:1040:in `require' from file:/C:/Users/DevAdmin/AppData/Local/Temp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-1682902661320758583.dir/webapp/WEB-INF/lib/jruby-rack-1.1.20.jar!/jruby/rack/rails/environment3.rb:25:in `load_environment' from file:/C:/Users/DevAdmin/AppData/Local/Temp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-1682902661320758583.dir/webapp/WEB-INF/lib/jruby-rack-1.1.20.jar!/jruby/rack/rails_booter.rb:83:in`load_environment' from <script>:1:in `(root)'

**Comment by sriv** [comment]
This seems to work fine for me, on Windows 10, Java 1.8. 

The [appveyor build](https://ci.appveyor.com/project/sriv/gauge-example-csharp/build/1.0.75) seems to like it as well :)

What version of Windows/Java are you on?

**Comment by tjuergens** [comment]
JDK 8 Update 102 introduced a change which causes this issue.
Download Update 101 or earlier from http://www.oracle.com/technetwork/java/archive-139210.html to get the sample application working.

**Comment by sriv** [comment]
Please download the [activeadmin-demo.war](https://bintray.com/gauge/activeadmin-demo/download_file?file_path=activeadmin-demo.war) and check. I have recompiled with JDK 1.8.121, so you should not see the error anymore.
